# Generated by Django 5.0.6 on 2024-06-04 17:01

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[catalog.models.User.validate_phone]),
        ),
    ]
