# Generated by Django 5.0.6 on 2024-06-04 18:32

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_branch_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveSmallIntegerField(default=18, validators=[catalog.models.User.validate_age]),
        ),
    ]
