# Generated by Django 5.0.6 on 2024-06-04 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
