# Generated by Django 5.0.6 on 2024-06-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_vacancy_remove_contact_name_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='promo',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
