# Generated by Django 5.0.6 on 2024-06-08 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_promo_code_alter_promo_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurableobject',
            name='owners',
        ),
        migrations.RemoveField(
            model_name='insurableobject',
            name='value',
        ),
    ]
