# Generated by Django 5.0.6 on 2024-06-09 15:11

import catalog.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_remove_insurableobject_owners_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='phone',
            field=models.CharField(max_length=13, validators=[catalog.models.Department.validate_phone]),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='agent',
            field=models.ForeignKey(limit_choices_to={'status': 'agent'}, on_delete=django.db.models.deletion.CASCADE, related_name='agent_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='client',
            field=models.ForeignKey(limit_choices_to={'status': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InsuranceRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('insurance_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.insurableobject')),
            ],
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='insurance_risk',
            field=models.ManyToManyField(to='catalog.insurancerisk'),
        ),
    ]
