# Generated by Django 5.0.6 on 2024-06-09 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_department_phone_alter_insurancepolicy_agent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancepolicy',
            name='client',
        ),
        migrations.RemoveField(
            model_name='insurancepolicy',
            name='department',
        ),
        migrations.RemoveField(
            model_name='insurancepolicy',
            name='insurable_object',
        ),
        migrations.RemoveField(
            model_name='insurancepolicy',
            name='insurance_amount',
        ),
        migrations.RemoveField(
            model_name='insurancepolicy',
            name='insurance_risk',
        ),
        migrations.RemoveField(
            model_name='insurancepolicy',
            name='insurance_type',
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('promo_code', models.CharField(max_length=8, null=True)),
                ('client', models.ForeignKey(limit_choices_to={'status': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_contracts', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='catalog.department')),
                ('insurable_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='catalog.insurableobject')),
                ('insurance_risk', models.ManyToManyField(to='catalog.insurancerisk')),
                ('insurance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='catalog.insurancetype')),
            ],
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='contract',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.contract'),
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
