# Generated by Django 5.0.6 on 2024-06-09 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_remove_insurancepolicy_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancerisk',
            name='insurance_object',
        ),
        migrations.AddField(
            model_name='insurancerisk',
            name='insurance_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='catalog.insurancetype'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='insurable_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='catalog.insurableobject'),
        ),
    ]
