# Generated by Django 5.0.6 on 2024-06-09 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_contract_insurable_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='insurance_risk',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='catalog.insurancerisk'),
        ),
    ]
