# Generated by Django 5.0.6 on 2024-06-09 20:54

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_contract_insurance_risk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='phone',
            field=models.CharField(max_length=15, validators=[catalog.models.Department.validate_phone]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[catalog.models.User.validate_phone]),
        ),
    ]
