# Generated by Django 5.0.6 on 2024-06-09 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_alter_department_phone_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancepolicy',
            name='tariff_rate',
        ),
        migrations.AddField(
            model_name='insurancetype',
            name='tariff_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='contract',
            name='insurance_risk',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='catalog.insurancerisk'),
        ),
    ]
