# Generated by Django 5.0.6 on 2024-06-09 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_remove_insurancepolicy_tariff_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 11, 1, 57, 43, 331594)),
        ),
    ]
