# Generated by Django 5.0.6 on 2024-06-09 23:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_promo_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='promo',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 11, 2, 48, 48, 937942)),
        ),
    ]
